api_platform:
    title: OLX Bot API
    version: 1.0.0
    openapi:
        contact:
            name: 'D Karpinski'
            url: 'https://dkarpinski.dev/'
            email: 'olxbot@dkarpinski.dev'
    formats:
        json:
            mime_types: [ 'application/json' ]

        jsonld:
            mime_types: [ 'application/ld+json' ]

        html:
            mime_types: [ 'text/html' ]

    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    swagger:
        versions: [ 3 ]
        api_keys:
            JWT:
                name: Authorization
                type: header
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        Doctrine\ORM\EntityNotFoundException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        Doctrine\ORM\Exception\MissingIdentifierField: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
        Symfony\Component\Filesystem\Exception\FileNotFoundException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_NOT_FOUND

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    show_webby: false
