version: '3.8'

services:
  database:
    container_name: olx-bot-db
    working_dir: /app
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: olxbot
      MYSQL_USER: olxbot
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - .:/app
      - ./mysql:/var/lib/mysql
  php:
    container_name: olx-bot-php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/app
    depends_on:
      - database
  nginx:
    container_name: olx-bot-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database