controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

integrations:
    resource:
        path: ../src/Integration/
        namespace: App\Integration
    type: attribute

auth:
    path: /api/auth
    methods: ['POST']